apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-eso
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wait
          image: bitnami/kubectl
          command:
            - sh
            - -c
            - |              
              until kubectl get deployment external-secrets -n external-secrets \
                -o jsonpath='{.status.conditions[?(@.type=="Available")].status}' \
                | grep True; do

                echo "Waiting for ESO..."
                sleep 5
              done

#              echo "Waiting for ESO to be ready..."
#
#              kubectl wait --for=condition=Available deployment \
#                -n external-secrets \
#                external-secrets \
#                --timeout=120s

#              echo "ESO is ready!"